title: Serly Sonam
theme: jekyll-theme-minimal
title_image: /assets/img/title-image.png
logo: /assets/img/logo.png
description: DevOps Engineer | CI/CD | AWS | Jenkins | Jira | Git | Docker | Ansible | Automation | Terraform | Kubernetes | Prometheus
show_downloads: true
google_analytics:
