title: Serly Sonam
description: DevOps Engineer | CI/CD | AWS | Jenkins | Jira | Git | Docker | Ansible | Automation | Terraform | Kubernetes | Prometheus
theme: jekyll-theme-minimal
#title_image: /assets/img/title-image.png
logo: /assets/img/PP_2:2.png
show_downloads: true
google_analytics:
